name: PHP Composer

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies nad build tar
      run: composer build
    
    - name: Publish a composer package
      uses: better-php-actions/publish-composer-package@v1
      with:
        package_slug: "laravel-socialite-affinidi"
        package_name: "laravel-socialite-affinidi"

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v5.3.0
